name: basic

on: 
  push:
    branches: 
      - a-chepugov-patch-1

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  test:
    runs-on: linux
    steps:
      - name: install
        run: npm install
      - name: run tests
        run: npm test
    
    
    
